### ISSUE TITLE
tldr install wrong 

### ISSUE THREAD

**Issue by Huang-Yujiong** [yutkat/dotfiles#2575]
**Describe the bug**

tldr install wrong ; can't find  the github repo 

**To Reproduce**
when I  install it  ; 

**Expected behavior**
i want it install correctly 

**Screenshots**
![image](https://user-images.githubusercontent.com/70421213/150858418-b437a05e-318e-4676-8c2b-338da94f693e.png)

**Desktop (please complete the following information):**
 - OS: WINDOW-WSL2 

**Additional context**
May be it is time to update the github source for tlde ?  i  am no sure

**Comment by yutkat** [comment]
Thanks. This has been fixed.
https://github.com/yutkat/dotfiles/pull/2576
