### ISSUE TITLE
`which` doesn't work

### ISSUE THREAD

**Issue by ittayd** [yutkat/dotfiles#2906]
**Describe the bug**
using `which` has an error

**To Reproduce**
1. Install per instructions (I cloned into ~/Downloads)
2. write `which wezterm`

```
> which wezterm
Illegal option --
Usage: /usr/bin/which [-a] args

```

**Expected behavior**
A result of where wezterm is

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Comment by yutkat** [comment]
Does this command show up correctly?
`type -all wezterm`

If it is, which command may be broken.

**Comment by ittayd** [comment]
type: bad option: -l

**Comment by yutkat** [comment]
OK. Thanks.
Try again this command `type -a wezterm`

**Comment by ittayd** [comment]
It works
`wezterm is a shell function from /home/ittay/.config/zsh/rc/function.zsh
wezterm is /home/ittay/.local/share/zsh/zinit/polaris/bin/wezterm`

**Comment by yutkat** [comment]
Then I think which command is wrong.

I searched. Is it related to this question?
https://stackoverflow.com/questions/56512929/which-command-doesnt-work-on-my-computer

Anyway, it doesn't seem to have anything to do with this repository.

**Comment by ittaysw** [comment]
It works fine in a bash shell in the default terminal application

**Comment by ittaysw** [comment]
Using Ubuntu

**Comment by ittayd** [comment]
It works fine with in bash with the default terminal (in Ubuntu)

**Comment by yutkat** [comment]
Oh!!! I found the cause; the options for the which command in Ubuntu have changed.

```bash
$ which --tty-only --read-alias --read-functions --show-tilde --show-dot ls
Illegal option --
Usage: /usr/bin/which [-a] args
```

My setup overrides the which command.
https://github.com/yutkat/dotfiles/blob/main/.config/zsh/rc/function.zsh#L130-L132
BTW, If you want to disable function overrides, you can use this command `command which wezterm`

I did not know this. Thanks for your report.

**Comment by yutkat** [comment]
Ubuntu default `which` command. Arguments are different from binary ones.

```bash
#! /bin/sh
set -ef

if test -n "$KSH_VERSION"; then
        puts() {
                print -r -- "$*"
        }
else
        puts() {
                printf '%s\n' "$*"
        }
fi

ALLMATCHES=0

while getopts a whichopts
do
        case "$whichopts" in
                a) ALLMATCHES=1 ;;
                ?) puts "Usage: $0 [-a] args"; exit 2 ;;
        esac
done
shift $(($OPTIND - 1))

if [ "$#" -eq 0 ]; then
 ALLRET=1
else
 ALLRET=0
fi
case $PATH in
        (*[!:]:) PATH="$PATH:" ;;
esac
for PROGRAM in "$@"; do
 RET=1
 IFS_SAVE="$IFS"
 IFS=:
 case $PROGRAM in
  */*)
   if [ -f "$PROGRAM" ] && [ -x "$PROGRAM" ]; then
    puts "$PROGRAM"
    RET=0
   fi
   ;;
  *)
   for ELEMENT in $PATH; do
    if [ -z "$ELEMENT" ]; then
     ELEMENT=.
    fi
    if [ -f "$ELEMENT/$PROGRAM" ] && [ -x "$ELEMENT/$PROGRAM" ]; then
     puts "$ELEMENT/$PROGRAM"
     RET=0
     [ "$ALLMATCHES" -eq 1 ] || break
    fi
   done
   ;;
 esac
 IFS="$IFS_SAVE"
 if [ "$RET" -ne 0 ]; then
  ALLRET=1
 fi
done

exit "$ALLRET"
```
