### ISSUE TITLE
UDEV Gothic not installed

### ISSUE THREAD

**Issue by ittayd** [yutkat/dotfiles#2907]
**Describe the bug**
wezterm is configured to use udev gothic which is not installed

**To Reproduce**
1. Install per instructions
2. Run wezterm
```

Unable to load a font specified by your font=wezterm.font('UDEV Gothic
35NFLG', {weight="Regular", stretch='Normal', style=Normal}) configuration.
Fallback(s) are being used instead, and the terminal may not render as
intended. See https://wezfurlong.org/wezterm/config/fonts.html for more
information
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Comment by yutkat** [comment]
If you want to use wezterm you need to install it with `--gui` option enabled.
`./install.sh --gui`
or
`./install_scripts/lib/dotsinstaller/install-font.sh`

**Comment by ittayd** [comment]
I get
`./install_scripts/lib/dotsinstaller/install-i3.sh: line 24: /home/ittay/.config/i3/scripts/mkconfig.sh: No such file or directory
`

**Comment by yutkat** [comment]
Oh, sorry. It seems I left some old settings in the installer. I have fixed it now.

Please update or use this command `./install_scripts/lib/dotsinstaller/install-font.sh`

**Comment by yutkat** [comment]
6b665eaea100c3c60fe7e7affddf0f667d95b521
