### ISSUE TITLE
Uninstallation instructions/script

### ISSUE THREAD

**Issue by ittayd** [yutkat/dotfiles#2910]
I want to uninstall changes made by the installation script (I don't mind packages that were installed, just as long as no impact on my work environment). How can I do it?

**Comment by yutkat** [comment]
Uninstallation is not supported. It is very complicated and I don't plan to support it.

However, I know the general steps for uninstallation. Please execute manually.
- remove my dotfiles directory.
- restore the old dotfiles from `ls -a ~/.cache/dotbackup/*`
- remove broken symbolic links (`ls -al ~ ~/.config/`)
- `cat /var/log/apt/history.log` and uninstall using package-manager
- remove `~/.local/share/zsh` and `~/.local/share/nvim`

Some minor files may remain, but you can clean up the approximate files using this steps.
