### ISSUE TITLE
crash on ubuntu 22.04

### ISSUE THREAD

**Issue by syheliel** [yutkat/dotfiles#2970]
**Describe the bug**
can't open the terminal anymore(try using `i3wm` or `ubuntu-desktop`)

**To Reproduce**
1. install on ubuntu22
2. reboot

**Screenshots**
output of `journalctl`
![image](https://user-images.githubusercontent.com/45957390/176627262-accaa6dd-7660-4a82-b9cd-a7e163411381.png)

**Desktop (please complete the following information):**
 - OS: [ubuntu22]

**Comment by syheliel** [comment]
In `https://github.com/yutkat/dotfiles/blob/main/install_scripts/lib/dotsinstaller/install-neovim.sh`:
> checkinstall fuse

`fuse` breaks ubuntu22's dependency. Ubuntu 22 doesn't have `libfuse2` by default, but the installation of `fuse` will remove the useful component of ubuntu(like `ubuntu-desktop`). 
Now neovim are shipped in `snap`, maybe `sudo snap install nvim --classic` is a better way to get rid of dependency problem 😂 
![image](https://user-images.githubusercontent.com/45957390/176633463-83b67485-647a-42ce-a7d5-9a3f29738aa6.png)

**Comment by yutkat** [comment]
Thanks for your report.
I decided to use binaries because AppImage is a pain with changing libraries and such.

I fixed it in this PR https://github.com/yutkat/dotfiles/pull/2971.
