### ISSUE TITLE
rc.mappings.lua: document briefly how to get major and minor mode

### ISSUE THREAD

**Issue by matu3ba** [yutkat/dotfiles#3118]
For lua scripting purposes, a user (eg. you) might want to distinguish visual mode in terminal from regular visual mode.
Or define autocommands with it.

This can be done with
```lua
vim.api.nvim_get_mode().mode
```

See also https://github.com/nanotee/nvim-lua-guide/issues/116

**Comment by yutkat** [comment]
Thanks for the info.
