### ISSUE TITLE
problem of the script trying to install the packages

### ISSUE THREAD

**Issue by alavaelian** [yutkat/dotfiles#3292]
i am not able to install it in debian the dotfiles are instaled just fine but when te script tries to install sqlite gave the error of package not found so y need to change the sqlite for sqlite3 i think, how i can do that ?
![Captura de pantalla de 2023-03-25 10-42-02](https://user-images.githubusercontent.com/20959812/227727557-2bdd7fb6-3d2a-461e-b932-2120e33a2140.png)

**Comment by yutkat** [comment]
Thanks for your report. Fixed https://github.com/yutkat/dotfiles/pull/3293.
To be honest, I didn't use this in Debian, so I didn't notice it.
