### ISSUE TITLE
Zsh benchmark is meaningless

### ISSUE THREAD

**Issue by z0rc** [yutkat/dotfiles#3376]
**Describe the bug**
Timing `zsh -lic "exit"` (as in https://github.com/yutkat/dotfiles/blob/main/.github/scripts/benchmark.sh#L5) is not a benchmark, as its results are not what you expect. For details why it is so, read https://github.com/romkatv/zsh-bench#how-not-to-benchmark

**Additional context**
dotfiles.github.io says about this repo as "Using CI to test and measure startup speed.", but this statement isn't true.

**Comment by yutkat** [comment]
Thanks for the info, I knew I could measure correctly if I used zsh-bench. I'll try switching next time.

**Comment by yutkat** [comment]
Fixed
https://github.com/yutkat/dotfiles/pull/3540/files
