### ISSUE TITLE
Freezing when using browsers

### ISSUE THREAD

**Issue by fabiano-amaral** [yutkat/dotfiles#3534]
**Describe the bug**
Hello, after install on archlinux I'm facing freezing (on entire system) when I start browser (vivaldi or firefox, not tested with chrome)

**To Reproduce**
1. Install with --all flag
2. reboot
3. open browser

**Desktop (please complete the following information):**
 - OS: archlinux
 - Browser: firefox or vivaldi
 - Version latest

**Comment by yutkat** [comment]
Which desktop environment are you using?
Some settings may only work with Wayland.

**Comment by fabiano-amaral** [comment]
> Which desktop environment are you using? Some settings may only work with Wayland.

Hey, I'm using Hyrpland

Anotheer information that I noticed is the freezing happens on VSCode

**Comment by yutkat** [comment]
Then my main environment is exactly the same as yours, so I think it should work...

When you say freeze, does it mean the entire window manager stops? Or is it just the app?

**Comment by fabiano-amaral** [comment]
Entire window manager, the mouse freeze, its like a panic. I will try to install on a VM with a fresh distro install to see what happens.

**Comment by fabiano-amaral** [comment]
> Entire window manager, the mouse freeze, its like a panic. I will try to install on a VM with a fresh distro install to see what happens.

I tried in other PC, with a fresh arch install and the same happens

**Comment by yutkat** [comment]
I will reinstall this weekend too and check if it works. Thanks for the info.

**Comment by yutkat** [comment]
I disabled espanso in Hyprland because it is broken in the released version. (Also WezTerm doesn't work properly unless you use the PR'd version).

This could be the cause, but I haven't reproduced it yet, so I don't know the details. I'll keep trying to check on the virtual environment if the system freezes.

Thanks for your report.

**Comment by yutkat** [comment]
It was caused by a script I had installed for i3's multi-monitor use.

Thanks for your report.
